### ISSUE TITLE
Make INodeConfiguration visible from GenericKnimeNodeModel

### ISSUE THREAD

**Issue by chahuistle** [genericworkflownodes/GenericKnimeNodes#101]
I'm currently working on conversion of KNIME workflows to other platforms, e.g., clusters. This conversion should also work for nodes imported via GKN. 

A simplification in the conversion and in the construction of the individual jobs could be achieved by accessing the `m_nodeConfig` member of the `GenericKnimeNodeModel` class. Currently, `m_nodeConfig` has the `private` access modifier and it would be very helpful to access it, even if it were in a read-only fashion, via a public _getter_ method.

**Comment by jpfeuffer** [comment]
see #171 ?

**Comment by chahuistle** [comment]
yeah!
