### ISSUE TITLE
Add getter method on GenericKnimeNodeModel to access its

### ISSUE THREAD

**Issue by chahuistle** [genericworkflownodes/GenericKnimeNodes#106]
A very useful feature (and a requirement for the KNIME2gUSE plug-in) would be to have access to the INodeConfiguration of a GenericKnimeNodeModel in order to generate a CTD (via CTDConfigurationWriter).

Adding a simple _getter_ method on GenericKnimeNodeMode would take care of this.

**Comment by jpfeuffer** [comment]
Addressed by #171?

**Comment by chahuistle** [comment]
this one too!
