### ISSUE TITLE
Flow->FileSplitter split file lists and provide output ports

### ISSUE THREAD

**Issue by timosachsenberg** [genericworkflownodes/GenericKnimeNodes#107]
Currently we have a FileMerger node to merge file lists. In many cases the number of input files is known so it would make sense to also have a FileSplitter node with a fixed number of output ports.
I bring this for practical reason as converting the file list to a table, splitting e.g. 1. and 2. row and converting them back to a URI is kind of complex for beginners. Many of our workflows would actually benefit (in terms of readability) from such a node that e.g. could be fixed to a small number of optional output files (e.g. 6 would cover 90% of all cases).
Any hints on if and how this could be done?

**Comment by jpfeuffer** [comment]
This was adressed at the KNIME Hackathon. I will prepare a PR soon.

**Comment by jpfeuffer** [comment]
#130
