### ISSUE TITLE
KNIME Jenkins Integration test for AsynchronousExecutor fails

### ISSUE THREAD

**Issue by jpfeuffer** [genericworkflownodes/GenericKnimeNodes#117]
See https://community.knime.org/jenkins/job/com.genericworkflownodes.knime.update-trunk/lastCompletedBuild/testReport/

If anyone knows something about this problem, I am happy to hear your input.

**Comment by jpfeuffer** [comment]
I saw that @chahuistle created that test. It actually runs fine on my local KNIME SDK. Can you think of a reason this might fail on the Jenkins?

**Comment by jpfeuffer** [comment]
Okay it seems to be a random error. Rerun fixed it. Maybe something to do with an appropriate sleeping time?

**Comment by temehi** [comment]
I am having this problem when I test my PR on Jenkins, two times this test exactly like your case passed on my local SDK, failed twice on Jenkins and passed on the third run. I am happy... ;) :tada:

**Comment by jpfeuffer** [comment]
Solved via #169
