### ISSUE TITLE
Failing process stdout: []

### ISSUE THREAD

**Issue by temehi** [genericworkflownodes/GenericKnimeNodes#143]
Whenever a node (SeqAn) fails to execute nothing is displayed at the KNIME console. We have only the following example output 

```
ERROR YaraMapper           0:46       Failing process stdout: []
ERROR YaraMapper           0:46       Failing process stderr: []
ERROR YaraMapper           0:46       Execute failed: Failed to execute node YaraMapper
```

**Comment by jpfeuffer** [comment]
Can this be closed? We saw it is the tool that writes no output without the "-v" option for reasons of piping, right?

**Comment by temehi** [comment]
Yes!
