### ISSUE TITLE
Question: Interoperability with e.g. File Handling nodes in KNIME

### ISSUE THREAD

**Issue by timosachsenberg** [genericworkflownodes/GenericKnimeNodes#156]
it would be nice to directly use e.g., the KNIME Zip Files node.
use cases might be compressing the output folder or writing a single zip file instead of a list of files. I think this is doable using flow variables but maybe there is a more elegant solution?

**Comment by jpfeuffer** [comment]
I think you would just need to do ... -> Port to URI -> Zip Files

**Comment by jpfeuffer** [comment]
Should work with single files and File Lists from Merger or Zip Loops

**Comment by jpfeuffer** [comment]
Can you confirm? Do you still think an extra node is necessary?

**Comment by timosachsenberg** [comment]
no I think it is fine. We could think about adding a simple example to the tutorial (maybe metanode part?) as it is a pretty common use case

**Comment by jpfeuffer** [comment]
https://github.com/OpenMS/Tutorials/issues/74
