### ISSUE TITLE
Make GKN compatible with CTD Schema v1.7

### ISSUE THREAD

**Issue by chahuistle** [genericworkflownodes/GenericKnimeNodes#177]
Version 1.7 of the CTD schema has been around for a while and support by GKN has not been implemented. This of course is a feature request.

**Comment by chahuistle** [comment]
At the top of my head, `bool` types are new in version 1.7 of the CTD schema.

**Comment by jpfeuffer** [comment]
https://github.com/FRED-2/ImmunoNodes/pull/23

**Comment by jpfeuffer** [comment]
at least the bool parsing is fixed in https://github.com/genericworkflownodes/GenericKnimeNodes/pull/212
