### ISSUE TITLE
Node configuration dialog unavailable after update

### ISSUE THREAD

**Issue by hendrikweisser** [genericworkflownodes/GenericKnimeNodes#178]
I hope this is the right place to report this problem: I have OpenMS installed in KNIME and have just updated it. The update changed the parameterization of one of the tools ("PeakPickerHiRes") - something that happens frequently for one tool or another.
If I now try to configure the corresponding node in an existing workflow, I get a dialog box saying:
> Dialog cannot be opened
> The dialog cannot be opened for the following reason: parameter report_FWHM_unit value is invalid

And in the console:
> WARN  LoadWorkflowRunnable                  Status: Warning: Loading model settings failed: invalid value for parameter PeakPickerHiRes.1.algorithm.report_FWHM_unit

The really annoying part is that I could easily fix the parameter problem if the configuration dialog would open! Furthermore, this prevents me from even looking at the parameters; otherwise I could copy them over to a "new" instance of the node from the Node Repository.

**Comment by jpfeuffer** [comment]
Hey, yes perfect place. I agree with you. We should change the behaviour from error to warning and maybe mark affected parameters in red. I will see what I can do.

**Comment by jpfeuffer** [comment]
I think I fixed this with recent commits in GKN. If you install the nightlies it should work.
