### ISSUE TITLE
Problem w/ minus-character in tool-name

### ISSUE THREAD

**Issue by MarcelSchumann** [genericworkflownodes/GenericKnimeNodes#19]
Better map '-' to an allowed character (like '_') for internal names (java classes, etc.) ... ;-)

---- Example: ---

 [copy] Copying 22 files to /tmp/temp.folder/lib.jar.bin
      [jar] Building jar: /tmp/temp.folder/library.jar

prepare:
   [delete] Deleting directory /tmp/temp.folder
    [mkdir] Created dir: /tmp/temp.folder/lib.jar.bin
    [javac] Compiling 377 source files to /tmp/temp.folder/lib.jar.bin
    [javac] /tmp/CADDSuite/src/org/ballproject/caddsuite/knime/nodes/TaGRes-train/TaGRes-trainNodeDialog.java:1: ';' expected
    [javac] package org.ballproject.caddsuite.knime.nodes.TaGRes-train;
    [javac]                                                     ^
    [javac] /tmp/CADDSuite/src/org/ballproject/caddsuite/knime/nodes/TaGRes-train/TaGRes-trainNodeDialog.java:6: '{' expected
    [javac] public class TaGRes-trainNodeDialog extends GenericKnimeNodeDialog
    [javac]                    ^
    [javac] /tmp/CADDSuite/src/org/ballproject/caddsuite/knime/nodes/TaGRes-train/TaGRes-trainNodeDialog.java:8: <identifier> expected
    [javac]     protected TaGRes-trainNodeDialog(NodeConfiguration config)
    [javac]                     ^
    [javac] /tmp/CADDSuite/src/org/ballproject/caddsuite/knime/nodes/TaGRes-train/TaGRes-trainNodeDialog.java:8: invalid method declaration; return type required
    [javac]     protected TaGRes-trainNodeDialog(NodeConfiguration config)

**Comment by roettig** [comment]
Should be fixed by 94f4a64a2cbc0306bfb5.
