### ISSUE TITLE
URI Ports not selectable when Reconfiguring/Setting up Metanodes

### ISSUE THREAD

**Issue by jpfeuffer** [genericworkflownodes/GenericKnimeNodes#190]
When you right-click -> setup on an existing meta-node and try to add a port that you e.g. forgot, URI ports are not available.

Maybe KNIME has to fix this in the FileHandling plugin.
@AlexanderFillbrunn

**Comment by AlexanderFillbrunn** [comment]
What do you mean by URIPorts? Your GKN port objects? I've got three entries for port objects from the GKN project (see attached screenshot). Generally, to make a port object turn up in the list, you only have to register it using the org.knime.core.PortType extension point, as you already did with those three.

<img width="545" alt="bildschirmfoto 2017-12-20 um 10 03 52" src="https://user-images.githubusercontent.com/3974661/34199318-ada44888-e56d-11e7-932e-78b1a04f26af.png">

Btw: You don't have to give your port objects such ultra-specific names. "File Store", "Prefix File Store" and "Reference File Store" or something similar would also work and looks much nicer in the GUI.

**Comment by jpfeuffer** [comment]
True, I will change the names but I was actually looking for a simple blue URI  Port from Knime

**Comment by AlexanderFillbrunn** [comment]
Those ports have the "hidden" flag set to true. I don't know why that is the case, though. I will ask Bernd Wiswedel for the reason and come back to you once I know more.

**Comment by AlexanderFillbrunn** [comment]
We fixed this and put it on our master branch, which means that it will be in our nightly builds and then in KNIME 3.6. Is that ok or is it so crucial that you need it in a bugfix release of 3.5?

A simple albeit a bit tedious workaround is to add a node with an outgoing URI port in the node and one with an ingoing one outside, expand the node, connect the two URI Port nodes, and then collapse into a metanode again.

**Comment by jpfeuffer** [comment]
Yes we used that workaround for a while now. Since more people started complaining I thought I bring it up ;) thanks a lot for the quick fix

**Comment by jpfeuffer** [comment]
Not urgent. We will wait for 3.6
