### ISSUE TITLE
List Options are not correctly transformed into KNIME Node Configuration

### ISSUE THREAD

**Issue by rrahn** [genericworkflownodes/GenericKnimeNodes#192]
If a tool has a list-option, such that multiple values can  be added by a repeated call of this option, KNIME fails to recognise this and issues the following error:

```
ERROR SeqanTcoffee         0:8        Execute failed: com.genericworkflownodes.knime.parameter.FileListParameter cannot be cast to com.genericworkflownodes.knime.parameter.FileParameter
````

In  my understanding it should be easy to provide a comma/semi-colon separated list in the configuration dialog for this parameter to mirror this behaviour. But I am not sure, what kind of limitations the configuration dialog has. But doing some regex to split the input string by a delimiter should not be a problem right?

**Comment by jpfeuffer** [comment]
Hmm what do you mean by "multiple values can be added by a repeated call of this option"?

**Comment by jpfeuffer** [comment]
Ah. -option "a" -option "b" -option "c"?

**Comment by jpfeuffer** [comment]
There is a specific parameter type that offers a list where selections can be added to. But if you want e.g. files or free-form strings, a separated string might be good.

**Comment by rrahn** [comment]
That means, selections are pre-configured right? 
No, it should be more generic, allowing the user to specify custom values.
Sometimes this could be a list of integers, which is hard to pre-configure.

**Comment by jpfeuffer** [comment]
Ok please see e.g. OpenMS/FileFilter peak_options:level

**Comment by rrahn** [comment]
Can you please add a proper link? 
I am lacking time for searching 😝

**Comment by jpfeuffer** [comment]
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/knime-plugin/generatedPluginSources/trunk/de.openms/src/de/openms/knime/nodes/FileFilter/

**Comment by jpfeuffer** [comment]
see config for the CTD

**Comment by rrahn** [comment]
thanks

**Comment by jpfeuffer** [comment]
But then I think that our executable actually expects the list to be specified after only one parameter.

**Comment by jpfeuffer** [comment]
https://github.com/genericworkflownodes/GenericKnimeNodes/blob/develop/com.genericworkflownodes.knime/src/com/genericworkflownodes/knime/execution/impl/CLICommandGenerator.java

Here the commands are generated based on the params that are read.
