### ISSUE TITLE
Support archives w/ one intermediate top-level directory 

### ISSUE THREAD

**Issue by MarcelSchumann** [genericworkflownodes/GenericKnimeNodes#20]
```
 [java] registering Category CADDSuite/
 [java] registering Category CADDSuite/IO/
 [java] PANIC - binary archive has no toplevel bin directory : /tmp//GENERIC_KNIME_NODES_PLUGINSRC/src/org/ballproject/caddsuite/knime/nodes/binres/binaries_mac_64.zip - EXITING
```

Because the archive contains:
|
|-- CADDSuite/
|------- bin
|------- data
|------- lib

As long as there is just one top-level directory (!= 'data', 'bin' or 'lib'), it should be accepted as well ...

**Comment by aiche** [comment]
Wont fix. The convention with not top-level directory is well documented and I see no reason for an intermediate directory.
