### ISSUE TITLE
Automatically creating ttd-file fails

### ISSUE THREAD

**Issue by MarcelSchumann** [genericworkflownodes/GenericKnimeNodes#21]
[propertyfile] Updating property file: /tmp/temp.folder/lib.jar.bin/org/ballproject/knime/baseplugin.properties
     [copy] Copying 24 files to /tmp/temp.folder/lib.jar.bin
      [jar] Building jar: /tmp/temp.folder/library.jar
     [copy] Copying 1 file to /media/sda6/GenericKnimeNodes
   [delete] Deleting directory /tmp/temp.folder

nodegen:

BUILD FAILED
/media/sda6/GenericKnimeNodes/build.xml:186: java.lang.NullPointerException
        at org.ballproject.knime.nodegeneration.NodeGenerator.generateDescriptors(Unknown Source)
        at org.ballproject.knime.nodegeneration.NodeGenerator.main(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)

**Comment by MarcelSchumann** [comment]
Ok, the new error message now is:

[propertyfile] Updating property file: /tmp/temp.folder/lib.jar.bin/org/ballproject/knime/baseplugin.properties
     [copy] Copying 56 files to /tmp/temp.folder/lib.jar.bin
      [jar] Building jar: /tmp/temp.folder/library.jar
     [copy] Copying 1 file to /media/sda6/GenericKnimeNodes
   [delete] Deleting directory /tmp/temp.folder

nodegen:
     [java] PANIC - could not find bin directory with executables at executabledir: /media/sda6/GenericKnimeNodes/BUILD/payload/CADDSuite/bin - EXITING
     [java] 
     [java] 

BUILD FAILED
/media/sda6/GenericKnimeNodes/build.xml:186: Java returned: 1

... and yes, the executables (*.bin) do reside in this directory ;-)

**Comment by MarcelSchumann** [comment]
Well, ok, it seems that currrently the user is excepted to specify the path to the _parent_ directory of the bin-folder, _not_ the bin-folder itself in the file 'plugin.properties'.

E.g.: 
/media/sda6/GenericKnimeNodes/BUILD/payload/CADDSuite/
instead of
/media/sda6/GenericKnimeNodes/BUILD/payload/CADDSuite/bin

Well, since the property in file 'plugin.properties' is called 'executabledir', the generator should actually better anticipate the latter path, I guess ...

**Comment by MarcelSchumann** [comment]
Anyway, if I do specify the expected parent-directory, generation of ttd's fails due to a different error: 

nodegen:
     [java] Aug 26, 2011 2:30:33 PM org.ballproject.knime.nodegeneration.NodeGenerator panic
     [java] SEVERE: PANIC - could not execute tool : /media/sda6/GenericKnimeNodes/BUILD/payload/CADDSuite/bin/gnuplot -write_par /tmp/TTD5903963250579688231 - EXITING

BUILD FAILED

**Comment by MarcelSchumann** [comment]
Furthermore (if tools not supporting '-write_par' are removed from bin-folder):

nodegen:
     [java] Aug 26, 2011 2:42:24 PM org.ballproject.knime.nodegeneration.NodeGenerator panic
     [java] SEVERE: PANIC - /tmp/GENERIC_KNIME_NODES_TTD/mimetypes.xml supplied as mimetypes.xml is no valid file - EXITING

Anyway, the file mentioned in this error-message does not seem to exist! 
Perhaps it was just written to a wrong location (or not written at all) ?!

**Comment by aiche** [comment]
The auto-generation code was removed making this issue invalid.
