### ISSUE TITLE
Null pointer exception for Nodes with no provided input but a required output prefix

### ISSUE THREAD

**Issue by kneubert** [genericworkflownodes/GenericKnimeNodes#259]
com.genericworkflownodes.knime.base.data.port.FileStorePrefixURIPortObject.getPrefix
` public String getPrefix()` returns 'null'
[null_pointer_exception.txt](https://github.com/genericworkflownodes/GenericKnimeNodes/files/3648302/null_pointer_exception.txt)

**Comment by jpfeuffer** [comment]
Hmm could also be that prefix ports do not support directories as prefix. Seems like prefixes are really meant as prefixes in the filename not the filepath. But in any case, it needs to be debugged. I don't have any prefix nodes though, so I probably can't help much.

**Comment by jpfeuffer** [comment]
https://github.com/genericworkflownodes/GenericKnimeNodes/blob/f3f3bee4280c8c89ba89f391929abd672d21f581/com.genericworkflownodes.knime/src/com/genericworkflownodes/knime/base/data/port/FileStorePrefixURIPortObject.java#L105

**Comment by kneubert** [comment]
#260 this seems to fix it. I tested it with my node (which has a prefix port as output and an optional file input port).
![fix_npe](https://user-images.githubusercontent.com/20301472/65596775-e5cd3f00-df97-11e9-95bd-d2699abbb92c.png)

**Comment by kneubert** [comment]
The problem does not exist with the recent GKN version, because of fallback:
GenericKnimeNodeModel.java (line 926)
` // If everything fails, use the nodename (generating type of nodes)`
` return m_nodeConfig.getName(); // + "_out" + outputIndex + iterationSuffix;`
