### ISSUE TITLE
Testing plugin/feature not working with KNIME 4.1 and upwards

### ISSUE THREAD

**Issue by danielesser** [genericworkflownodes/GenericKnimeNodes#265]
GenericKnimeNodes generates testing plugins and features to execute test workflows. The generated testing modules require the feature `org.knime.features.testingapplication` see [here](https://github.com/genericworkflownodes/GenericKnimeNodes/blob/9082c6ab43e46c21fb5c1f091f9043cde2fb029d/com.genericworkflownodes.knime.node_generator/src/com/genericworkflownodes/knime/nodegeneration/templates/testingfeature/testingfeature.xml.template).

KNIME has recently (and silently) changed the name of this feature to `org.knime.features.testing.application` (note the dot between `testing` and `application`). For target platforms KNIME 4.1 and upwards, testing features can no longer be installed and executed. More infos [here](https://forum.knime.com/t/testing-framework/19890).

**Comment by jpfeuffer** [comment]
So, how are we supposed to go forward with this? Is there a way to specify an "either .. or" for a plugin dependency?
Or do we have to break backwards-compatibility and add weird 4.1+ dependencies just because of a rename?

**Comment by jpfeuffer** [comment]
So, I just removed it in the referenced PR.
Let's see what they say in the forum
https://forum.knime.com/t/testingapplication-feature/20398
