### ISSUE TITLE
Missing integration of Eclipse+Git in wiki page "Using Eclipse and GKN"

### ISSUE THREAD

**Issue by bkahlert** [genericworkflownodes/GenericKnimeNodes#30]
The wiki page "Using Eclipse and GKN" well describes how to use Eclipse to work in GKN.
What the wiki page should also offer is an explication of how to use Eclipse's Git plugin to avoid the command line at all.

**Comment by aiche** [comment]
I think is not our intention. Users should decide on their own which way of using git they want to choose. Beside this their should be numerous tutorials on how to use egit.
