### ISSUE TITLE
Knime: WARN  TargetedFileConverter 3:492      Failed to find matching binary.

### ISSUE THREAD

**Issue by bruadi** [genericworkflownodes/GenericKnimeNodes#300]
I have now updated to the latest Knime version 4.7.4. Now I can't use the OpenMS nodes anymore. I always get messages like this: 

WARN TargetedFileConverter 3:492 No binary could be found for the TargetedFileConverter executable. Please refer to the GKN troubleshooting guide on how to provide missing binaries (see https://github.com/genericworkflownodes/GenericKnimeNodes/wiki/How-to-handle-missing-binaries).
WARN TargetedFileConverter 3:492 No matching binary file could be found.

I am working with a MacBook (apple silicon)... . 
How do I get the problem solved?

Greetings

**Comment by jpfeuffer** [comment]
Sorry but I don't know how to support Silicon. You would need to reach out to KNIME to help me.

**Comment by bruadi** [comment]
If I install the OpenMS Extension for 4.6 (KNIME Community Extensions (Trusted) - https://update.knime.com/community-contributions/trusted/4.6) every node works as long as I also work with a KNIME 4.6 version. However, if I update Knime to a 4.7 version, KNIME Community Extensions (Trusted) - https://update.knime.com/community-contributions/trusted/4.7 is not even listed here for OpenMS to install this extension. 

Since the OpenMS nodes works on version 4.6, it's probably not Silicon... . Is there any reason why the OpenMS extension is not listed on 4.7?

Greetings

**Comment by jpfeuffer** [comment]
Well there was no Silicon release for KNIME 4.6. That's the difference I think.

**Comment by bruadi** [comment]
You are right! Have now installed Knime 4.7.4 for intel instead of silicon. It works. Thanks a lot!

**Comment by jpfeuffer** [comment]
Perfect. I hope we can provide real silicon builds soon.
