### ISSUE TITLE
Jgit timestamp does not reside in extras anymore

### ISSUE THREAD

**Issue by jpfeuffer** [genericworkflownodes/GenericKnimeNodes#304]
https://github.com/genericworkflownodes/GenericKnimeNodes/blob/3fa2f4ba8f7e9360dd6cb8bd9df5d9b747b3d7a2/com.genericworkflownodes.maven/pom.xml#L93

See Jenkins logs of the failed runs.

https://github.com/eclipse-tycho/tycho/issues/915

**Comment by poshul** [comment]
Okay, what am I missing here? The errors in Jenkins point to this not existing in the maven repo, but it's clearly there: https://repo.maven.apache.org/maven2/org/eclipse/tycho/tycho-buildtimestamp-jgit/3.0.1/

What are "extras"?

**Comment by poshul** [comment]
Deleted that question. I just spent too much time staring at the errors and missed the change.

**Comment by jpfeuffer** [comment]
Yes maven logs are humongous 😔

**Comment by poshul** [comment]
> Yes maven logs are humongous 😔

I'd spent so long staring at them that the words blurred together.
