### ISSUE TITLE
Separation into two projects

### ISSUE THREAD

**Issue by bkahlert** [genericworkflownodes/GenericKnimeNodes#31]
There are currently two things the GKN plugin is responsible for:
1) Creation of KNIME nodes
2) Serving a a KNIME node

The two purposes should be reflected by two projects.

**Comment by aiche** [comment]
fixed in 1dd2e8e868f98bebf0e938c176dcf576f8a71f6d

we now have two projects, one which provides the base plugin and common functionality and one which is only needed for plugin generation
