### ISSUE TITLE
New Namespace

### ISSUE THREAD

**Issue by bkahlert** [genericworkflownodes/GenericKnimeNodes#32]
We should refactor everything to have a new namespace
since the current namespace "org.ballproject.knime" only exists for historical reasons.

Any recommendations?

I see two options:
1) sub namespace: org.knime.generic_nodes
2) independent namespace like org.generic_knime_nodes (domain gkn.org is not available anymore so no option)

**Comment by aiche** [comment]
I would suggest something like 

`{de|org}.genericknimenodes.*`

since the underscore is not available for host names. I could talk to the IT staff here if they could register the associated domain for us.

**Comment by aiche** [comment]
A (not so attractive) alternative would be to use the project page as namespace 

`com.github.roettig.genericknimenodes.*`

**Comment by bkahlert** [comment]
or `org.knime.genericnodes.*`?

**Comment by aiche** [comment]
we now use the new namespace 

`com.genericworkflownodes.knime.*`

All new classes should be created in this namespace and old classes will be moved while working on them.
