### ISSUE TITLE
Unzip node binaries on installation

### ISSUE THREAD

**Issue by bkahlert** [genericworkflownodes/GenericKnimeNodes#35]
... and not on KNIME start.

@see PluginActivator.java of generated plugins

**Comment by chahuistle** [comment]
Hi,

Would you care to ellaborate on this issue? I mean, what is the value
of unzipping node binaries on installation?

Regards,
Luis

On Tue, Mar 27, 2012 at 4:44 PM, Björn Kahlert
reply@reply.github.com
wrote:

> ... and not on KNIME start.
> 
> @see PluginActivator.java of generated plugins
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/roettig/GenericKnimeNodes/issues/35

## 

Luis Javier de la Garza Treviño

**Comment by bkahlert** [comment]
Hi Luis,

it is possible that shipped binaries are bigger than some KB.
As you surely know Eclipse takes it's time to start... every delay would be greatly unwelcome.

By unzipping the shipped data only once (at installation) instead of once per start
we keep the Eclipse start time instead of increasing it.

I'm not sure when I will find the time. First I'm working on the ability to distribute platform specific binaries
just for the user's platform instead of all existing binaries.

Regards,
Björn

**Comment by aiche** [comment]
fixed in b2b95669e2e42c076e3c9b28fdfe8834217956ff
