### ISSUE TITLE
Create extension point for IExecutor

### ISSUE THREAD

**Issue by aiche** [genericworkflownodes/GenericKnimeNodes#39]
The current base plugin provides three different implementations of IExecutor which are currently sufficient but we should make it possible to extend the IExecutor interface for specific plugins.

**Comment by aiche** [comment]
This would also ease the instantiation which is currently handled via `Class.forName()`

**Comment by AlexanderFillbrunn** [comment]
Has this been done? There is an "Executor" extension point for IToolExecutors and the IExecutor interface does not exist. Was it renamed?

**Comment by jpfeuffer** [comment]
I think this looks solved! I also would not know what to do here. Reopen if anyone has more comments.
