### ISSUE TITLE
Add base and custom plugin deployment in ant.xml

### ISSUE THREAD

**Issue by chahuistle** [genericworkflownodes/GenericKnimeNodes#42]
After either the base or custom plugins have been built, one must manually copy the plugin jar file to the `${knime.sdk}/plugins` folder, which is really annoying.

It would be nice to have ant targets that do this,

**Comment by chahuistle** [comment]
Fixed on commit a0257ee16bb7a6e912c0a47617953e31aca945d1

**Comment by aiche** [comment]
Reverted a0257ee16bb7a6e912c0a47617953e31aca945d1 in a5103807fd712ab827ced000ab45267a7c946a12 

We do not commit directly to master. Please fix this issue on the develop branch

**Comment by chahuistle** [comment]
After disussing with aiche about this issue, we decided not to implement it. The idea behind is to use KNIME's SDK to do development and with it, the ant scripts are not needed in the development cycle.
