### ISSUE TITLE
Add the ability to include environment variables for external tools

### ISSUE THREAD

**Issue by chahuistle** [genericworkflownodes/GenericKnimeNodes#50]
Some tools need environment variables to be set in order to work properly. This can be done for internal tools, but it is not possible to do so for external tools.

It should be fairly easy to include this information in the CTD and pass it on to GKN's runtime environment.

**Comment by aiche** [comment]
It is not that easy .. we can only include the fact that a specific env variable is needed through the CTD, but not its value. Then we would need to expose this setting in the Preferences dialog. The second problem is: Is an env variable a project or tool specific setting. In the first case we would need to integrate it into the plugin.properties. 

I actually would prefer to ignore this problem for now. I think for all major platforms this problem can be solved outside of KNIME 
- Windows' env variables are global in the sence that every tool sees them
- For linux the .profile should solve it
- For Mac OS you can use http://www.dowdandassociates.com/content/howto-set-environment-variable-mac-os-x-etclaunchdconf or ~/.MacOSX/environment.plist

**Comment by chahuistle** [comment]
This feature request was left alone for a while. There have been some changes done in GenericKnimeNodes.

> It should be fairly easy to include this information in the CTD...

Yes, it is easy. But then, we would need to update the schema. Plus, there's a couple of workarounds for developers (e.g., setting the variables manually in Eclipse or in the computer).

> and pass it on to GKN's runtime environment.

This is exactly the purpose of the `binaries.ini` plugin file, which did not exist at the time this issue/feature request was created.

So in my opinion, this item no longer applies.
