### ISSUE TITLE
Allow directory payloads instead of ZIP files.

### ISSUE THREAD

**Issue by holtgrewe** [genericworkflownodes/GenericKnimeNodes#54]
It would be very convenient if users could provide a "binaries_lnx_64", for example.

This way, they would save the compression step and versionizing single binaries inside the archive would become easier.

As far as I can see, instead of copying the ZIP file in the GenericKnimeNode code, the code could simply create the ZIP file from a ".d" file if it already exists.

In the case that there are both ZIP files and .d directories, ZIP files could be preferred and a warning printed back to the user.

**Comment by aiche** [comment]
Wontfix. For debugging purposes it is easier to use the user-defined binaries feature instead of the payload. If it comes to shipping I see no benefit in using directories.
