### ISSUE TITLE
Allow underscore in tool names

### ISSUE THREAD

**Issue by holtgrewe** [genericworkflownodes/GenericKnimeNodes#55]
As far as I can tell, it is not allowed to have underscore in tool names. This also means that binaries cannot contain underscores.

Is it possible to allow this?

SeqAn apps use underscore_lowercase_naming instead of CamelCaseNaming.

**Comment by aiche** [comment]
I think we should stick to the convention to use only camel case names for the nodes, but we can add an extra executable-name field to the CTD to enable users to set custom, non-camel-case executable names for their tools.

**Comment by holtgrewe** [comment]
Sounds good to me.

**Comment by aiche** [comment]
Implemented in 0c98f4a354b5576c8872430796eb19ce325175a2
