### ISSUE TITLE
Settings Editor Bug

### ISSUE THREAD

**Issue by holtgrewe** [genericworkflownodes/GenericKnimeNodes#57]
To reproduce:

Open a generic KNIME node with a string choice field.
Click on the value, a drop down appears.
Select another value
Click "Apply", then "Close" or click "OK".
Re-open the configuration editor.

What happens: The setting stays in its previous value.

What I expect to happen: The setting should be updated.

**Comment by aiche** [comment]
fixed in 446a0c56d2334814236193871e598f861f065d86
