### ISSUE TITLE
Save stdout/stderr of the last execution of a node

### ISSUE THREAD

**Issue by chahuistle** [genericworkflownodes/GenericKnimeNodes#69]
It would be helpful to keep the stdout and stderr from the last execution of a node. 

Some nodes (i.e., GridBuilder in CADDSuite) do heavy number-crunching and output their state to stdout. It would be useful to know if the node is stalled or still executing by inspecting its stdout.

**Comment by jpfeuffer** [comment]
Do you mean live-update of the stdout/err?
I was think about that, too but I am not sure how we would realize this. I think the view is not ready during execution. We could print it to console but this gets messy.
See #174
