### ISSUE TITLE
Default file extension for Output File

### ISSUE THREAD

**Issue by weese** [genericworkflownodes/GenericKnimeNodes#74]
Hi,

right now, the output file format of a tool must be specified at the tool node. To export a file (via an Output File node) it is again necessary to specify a file name _plus_ extension.

Would it be possible to set a default extension for the Output File node that will be preset in the file dialog based on the input file.

Cheers,
Dave

**Comment by aiche** [comment]
The idea is good, but in the current implementation does not allow setting a file extension on the dialog components. I will ask the KNIME people if there is a possibility to expose this functionality.

**Comment by weese** [comment]
Thank you very much for your quick reply. I really appreciate your work on this plugin!
Keep up the good work!

Cheers,
Dave

Von meinem iPad gesendet

Am 25.02.2013 um 18:26 schrieb "Stephan Aiche" <notifications@github.com<mailto:notifications@github.com>>:

The idea is good, but in the current implementation does not allow setting a file extension on the dialog components. I will ask the KNIME people if there is a possibility to expose this functionality.

**Comment by aiche** [comment]
We can circumvent this problem by implementing the dialog on our own. This issue will be started after we switched to the new MIMETypeEntries from KNIME 2.7.
