### ISSUE TITLE
Switch generated node to NodeSetFactory

### ISSUE THREAD

**Issue by aiche** [genericworkflownodes/GenericKnimeNodes#80]
Currently we generate java code for every node, instead we could switch to the NodeSetFactory to centralize the generated code.

**Comment by jpfeuffer** [comment]
We will tackle this with @alexanderfillbrunn on the developer meeting.
Resources:
- A similar implementation
https://github.com/chemalot/chemalot_knime/blob/master/com.genentech.knime/src/com/genentech/knime/dynamicNode/AbstractCmdSdfNodeFactory.java
- Source docs
https://tech.knime.org/docs/api/org/knime/core/node/NodeSetFactory.html

**Comment by jpfeuffer** [comment]
See #162. In progress.

**Comment by jpfeuffer** [comment]
Done. Currently supports both statically generated and dynamic nodes.
