### ISSUE TITLE
Update README/build.xml to reflect the latest changes in the node generation process

### ISSUE THREAD

**Issue by julianu** [genericworkflownodes/GenericKnimeNodes#86]
was: compile error: package org.knime.base.filehandling.mime does not exist

With the newest Knime release 2.7.2 I can not compile the sources but always get the error
[javac] /home/julian/src/GenericKnimeNodes/com.genericworkflownodes.knime/src/com/genericworkflownodes/knime/generic_node/GenericKnimeNodeModel.java:32: package org.knime.base.filehandling.mime does not exist

This error is repeated for all the lines trying to import org.knime.base.filehandling.mime.
I also searched in the SDK/plugin JARs and did not find this package there.

**Comment by aiche** [comment]
To get rid of this error you need to install the "KNIME File Handling Nodes" extension from KNIME Labs. Sorry we didn't update the install instructions yet.

**Comment by julianu** [comment]
Thanks, the compiling works now.

After creating an emty payload directory in the sample-openms and running ant with 

``` shell
-Dplugin.dir=/path/to/GenericKnimeNodes/com.genericworkflownodes.knime.node_generator/sample-openms/
```

the compilations run without errors.
Interestingly I get two files with the names com.genericworkflownodes.knime_0.7.0.jar and org.ballproject.knime.node_generator.jar and not with openms or something in the name (tried this also with another small own sample).
But after copying these JARs into the plugin directory and starting Knime, I get a heap of errors like this one:

``` shell
ERROR    RepositoryManager   Node com.genericworkflownodes.knime.nodes.io.importer.MimeFileImporterNodeFactory' from plugin 'com.genericworkflownodes.knime' could not be created: Can't load factory class for node: com.genericworkflownodes.knime.nodes.io.importer.MimeFileImporterNodeFactory The corresponding plugin bundle could not be activated!
```

As a side notion: the SDK seems not to be needed, I can compile with the same (unfortunately not working) results against the normal Linux download of Knime.

**Comment by aiche** [comment]
Once again this a problem with the documentation. We changed the default behavior of the ant script to just produce the source code of the nodes, but not to compile them. After generation you can load the generated source code and the source code of the generic knime nodes plugin in your SDK and work with the nodes. Since we currently change a lot of things in the develop branch this problem will stay for a while. If I have time I will try to update the documentation and give some hints how to work with the generated source code. 

To generate the sources in user defined directory please add the following flag to your ant call

```
-D custom.plugin.build.src=/path/where/the/node/sources/should/be/generated/
```

**Comment by julianu** [comment]
It's working with these settings, thank you!

**Comment by julianu** [comment]
Thanks a lot.
Now I need only one more thing and I would be really happy: is there an easy way or example how to call methods in a JAR (i.e. to define it in the CTD) for a JAR either bundled or somewhere else on the computer? And do I have to perform the bundling of the JAR in the SDK? Putting it into the "contributing-plugins" directory is ignored here.
Actually a link to the CTD-schema would be great as well... but maybe I am just to stupid too google it.
But as I am off for the next week, I may also just revisit your documentation improvements as well.

**Comment by aiche** [comment]
What  exactly do you want to achieve when calling a function from a jar file. The idea behind the CTD/GenericKNIMENodes project is to bundle command line tools in a convenient way and make them available as KNIME nodes. So calling a function from a jar file is not exactly what we are targeting with this project. The `contributing-plugins` directory is used to ship additional plugins with the generated ones, e.g., if you have custom KNIME nodes that you want to add to distribute alongside the generated ones. But in the `contributing-plugins` we expect source code, not a compiled jar file. But maybe I just misunderstood what you want to achieve. 

The CTD schema is embedded in our source repository. 

https://github.com/genericworkflownodes/GenericKnimeNodes/blob/develop/com.genericworkflownodes.knime/src/com/genericworkflownodes/knime/schemas/CTD.xsd

**Comment by julianu** [comment]
The actual intention was to call java and execute different main()-methods in a JAR with different nodes.
I have this running now with help of the schemata, thank you again.

**Comment by jpfeuffer** [comment]
I will update the docu once we switched to dynamic node generation #162
